//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int id { get; set; }
        public object Id { get; internal set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public string Age { get; set; }
        public Nullable<int> DepId { get; set; }
        public string Email { get; set; }
        public string Image { get; set; }
        public string SSN { get; set; }
        public string Teacher { get; set; }
    
        public virtual Departements Departements { get; set; }
    }
}
